-- =============================================================================
-- 01_campaign_wallets.sql
-- onchain-attribution-kit | Dune Analytics Query Pack
-- =============================================================================
--
-- PURPOSE:
--   Base CTE: loads wallet attribution events from a CSV uploaded to Dune.
--   This is the foundation for all other queries in the pack.
--   Every downstream query references campaign_wallets from this CTE.
--
-- REQUIRED INPUT:
--   A CSV file uploaded to Dune containing your attribution events.
--   Use data/events.csv generated by the onchain-attribution-kit server.
--   Upload via: Dune > My Uploads > Upload CSV
--
-- REPLACE-ME VARIABLES:
--   - `your_upload_table_name` below: replace with the actual table name from your upload
--     Example: dune.gabriel_mangabeira.dataset_attribution_events_2026_05
--
-- COLUMNS EXPECTED IN UPLOAD:
--   wallet_address, campaign_id, utm_source, utm_medium, utm_campaign,
--   utm_content, utm_term, ref, kol, landing_url, referrer, connected_at,
--   session_id, chain_id, attribution_model
--
-- LIMITATIONS:
--   - This query relies on the attribution window being correctly applied
--     by the capture snippet. Late wallet connects (beyond the window) are not tracked.
--   - Wallets are identified by address only. Multi-wallet users appear as separate rows.
--   - If a wallet connected multiple times (e.g., reconnect), de-duplication uses
--     MIN(connected_at) to keep only the first attribution event per wallet.
--
-- =============================================================================

WITH raw_events AS (
  SELECT
    wallet_address,
    campaign_id,
    utm_source,
    utm_medium,
    utm_campaign,
    utm_content,
    utm_term,
    ref,
    kol,
    landing_url,
    referrer,
    CAST(connected_at AS TIMESTAMP) AS connected_at,
    session_id,
    TRY_CAST(chain_id AS INTEGER) AS chain_id,
    attribution_model
  FROM
    your_upload_table_name  -- REPLACE: your Dune CSV upload table name here
),

-- De-duplicate: keep only the first attribution event per wallet address.
-- Last-touch attribution: each wallet gets one source/campaign assignment.
campaign_wallets AS (
  SELECT
    wallet_address,
    -- Attribution fields from the first (earliest) connect event
    FIRST_VALUE(campaign_id)   OVER w AS campaign_id,
    FIRST_VALUE(utm_source)    OVER w AS utm_source,
    FIRST_VALUE(utm_medium)    OVER w AS utm_medium,
    FIRST_VALUE(utm_campaign)  OVER w AS utm_campaign,
    FIRST_VALUE(utm_content)   OVER w AS utm_content,
    FIRST_VALUE(utm_term)      OVER w AS utm_term,
    FIRST_VALUE(ref)           OVER w AS ref,
    FIRST_VALUE(kol)           OVER w AS kol,
    FIRST_VALUE(landing_url)   OVER w AS landing_url,
    FIRST_VALUE(chain_id)      OVER w AS chain_id,
    MIN(connected_at)          OVER w AS first_seen,
    ROW_NUMBER()               OVER w AS rn
  FROM raw_events
  WINDOW w AS (PARTITION BY wallet_address ORDER BY connected_at ASC)
)

-- Final output: one row per attributed wallet
SELECT
  wallet_address,
  campaign_id,
  utm_source,
  utm_medium,
  utm_campaign,
  utm_content,
  utm_term,
  ref,
  kol,
  landing_url,
  chain_id,
  first_seen
FROM campaign_wallets
WHERE rn = 1
ORDER BY first_seen DESC;
